### ISSUE TITLE
Main - NFT Collector Story #6

### ISSUE THREAD

**Issue by sarafanciulli** [SecretDecks/Website#12]
###  Story sub N1
As a Tarot enthusiast I want to keep myself up to date about any news regarding the project, without swiping too many pages, before I dig into something that interests me a lot. 
I see on the header an Arcana section. 
I immediately know this is what I’m looking for

-> Links to github updated section or any other articles about SD

**Goals**
This story will allow keeping members up to date in an easy way and through our website

**Specifications**
Arcana section
Links to dedicated github channel

**Tasks**
 create Miro wireframe for landing page (see Figma >website >page6 )
discuss how to automatically organize page automation from github + manual entries

**Comment by DanM3rcurius** [comment]
Hi Sara, we already have a user Tarot Story. 
Why is the issue/task named NFT collector  story? 
Also I mentioned to not use the term "user".

Let's take a step back and tell me what you did and why?

**Comment by sarafanciulli** [comment]
user delated I ve just saw your previous one and I got confused. As it is NFT collectors story and not members story I imagine an NFT collector ,which maybe me a member or not, who want to be easly informed about the last topics about the project...On the SD website we dedicate an Arcana section to let this happens. that's why I wrote sub n1 as it could be a substory...
