### ISSUE TITLE
create Temperance card mockup @sarafanciulli ?

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Website#13]
## Goal
modify temperance card to not be recognizable by bots as copyright material

**Comment by sarafanciulli** [comment]
Thinking about it…but it would be nice to figure out first how cards will look like, to keep the same style. I think open a discussion about that it would be great!

**Comment by DanM3rcurius** [comment]
Yes. The first task would be to create some ideas in a brainstorm. I intentionally didn't put constraints so to see where you would take this. There's not real visual identity yet set. @tamagit80 and you might want to start a coop identity guide. 
In your Figma file you already started with something similar on the "elements" sheet if I remember correctly?

**Comment by DanM3rcurius** [comment]
![XIV-temperance-rework](https://user-images.githubusercontent.com/80257662/139224453-37a14f5a-84d3-44d9-bc36-742d04c56789.png)
first version done

**Comment by DanM3rcurius** [comment]
![XIV-temperance-rework-3](https://user-images.githubusercontent.com/80257662/139288420-5a06f941-7a73-4d6f-be67-cdc8400d641d.png)

new card mockup

**Comment by DanM3rcurius** [comment]
![temperance-artist](https://user-images.githubusercontent.com/80257662/142270740-579eac83-063b-4b1f-9b53-5bca0235a2c3.png)

@wlstylr new version
