### ISSUE TITLE
create artist blurb (to entice artists to join discord or fill out form) @evolayak

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Website#19]
## Goal
a short blurb enticing artists and creators to follow the links (artist form and Discord)

## Proposed text
(Are you an artist?)
Do you love to create?
Have you heard of tarot?
If one above answered with a tentative yes, join Discord or reach out (form)

**Comment by evolayak** [comment]
(Are you an artist?)
Do you love to create or have you heard of Tarot?
Join us on Discord or reach out (form)

**Comment by DanM3rcurius** [comment]
Can you please rephrase the sentence below "Choose your card" @evolayak 
![Screenshot 2021-10-26 at 21 29 02](https://user-images.githubusercontent.com/80257662/138948050-7a65b254-8b18-49d3-b509-2f40176a9006.png)

**Comment by DanM3rcurius** [comment]
perfect, thanks Heather!

**Comment by DanM3rcurius** [comment]
Do you love to create or have you heard of Tarot?
Join us on [Discord](https://discord.gg/gQR54Bs3uj) or reach out (form link)
