### ISSUE TITLE
Find name (title) for (artist) card

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Website#20]

**Comment by DanM3rcurius** [comment]
I suggest: CREATE

**Comment by DanM3rcurius** [comment]
CREATOR

**Comment by sarafanciulli** [comment]
have we decided already the other name? one is "the metaverse" right? 
I feel "the creator" a bit like the God... maybe something unconvetional, like "The Utopian" ?? (or Utopianer)

**Comment by DanM3rcurius** [comment]
I like the Utopian! Is it too specific if we want to reach Artists/creatives?
