### ISSUE TITLE
create Tarot blurb (to entice tarot heads to join discord) @evolayak

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Website#21]
## Goal
a short blurb enticing Tarot enthusiasts and esoterics to follow the links (GitBook and Discord)

## Proposed text
(Are you an esoteric?)
Do you love to explore yourself?
Have you heard of Tarot?
If one above answered with a tentative yes, join Discord or read the Lore

**Comment by evolayak** [comment]
Are you into self-exploration or heard of Tarot?
Join us on Discord or read 'the Lore'

**Comment by DanM3rcurius** [comment]
![Screenshot 2021-10-26 at 21 43 08](https://user-images.githubusercontent.com/80257662/138949768-04f62a10-d15f-43ad-925d-763b3bf459ad.png)

**Comment by DanM3rcurius** [comment]
Are you into self-exploration or heard of Tarot?
Join us on [Discord](https://discord.gg/q9d9AeCfaC) or read our [Arcana](https://secretdecks.gitbook.io/arcana/sd-dapp-metaverse/the-tarot-metaverse-experience)
